services:
  flask-app:
    build: .
    container_name: currency-flask
    restart: always

  nginx:
    image: nginx:latest
    container_name: currency-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-app
